version: '3'

services:
  # PHP Service
  php:
    image: capimichi-php:8.1-apache
    container_name: lamp_php
    ports:
      - "8085:80"
    volumes:
      - ./:/var/www/html
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    depends_on:
      - mysql
    networks:
      - json_to_class_network

  # MySQL Service
  mysql:
    image: mysql:latest
    container_name: lamp_mysql
    ports:
      - "3307:3306"
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - "~/mysql/json_to_class:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sy_json_to_class
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - json_to_class_network

networks:
  json_to_class_network:
